# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.twig.app_extension:
    public:    false
    class:     AppBundle\Twig\AppExtension
    arguments: 
      doctrine : '@doctrine'
    tags:
      - { name: twig.extension }
