AppBundle\Entity\Habitaciones:
    type: entity
    table: habitaciones
    indexes:
        idTipoHab:
            columns:
                - idTipoHab
        idHotel:
            columns:
                - idHotel
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 64
            options:
                fixed: false
        planta:
            type: integer
            nullable: false
            options:
                unsigned: false
        idtipohab:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: idTipoHab
        idhotel:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: idHotel
        estadisponible:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: estaDisponible
    lifecycleCallbacks: {  }
