AppBundle\Entity\Tipohabs:
    type: entity
    table: tipohabs
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tipohab:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
            column: tipoHab
        preciobase:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: precioBase
    lifecycleCallbacks: {  }
