AppBundle\Entity\Usuarios:
    type: entity
    table: usuarios
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 16
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 55
            options:
                fixed: false
        permisos:
            type: string
            nullable: false
            length: 16
            options:
                fixed: false
        fecharegistro:
            type: datetime
            nullable: false
            column: fechaRegistro
    lifecycleCallbacks: {  }
